### ISSUE TITLE
Documentation could not be created.

### ISSUE THREAD

**Issue by FrostyFrost** [lluiscamino/phpDoc2pdf#2]
Hello! Tried to create documentation using command but got the error:
php phpDoc2pdf.phar create . .\docs
Documentation could not be created.

If I use phpDocumentor it works properly.
What might be the problem?
Best regards, Andrew.

UPD: I should write full path like php phpDoc2pdf.phar create C:\Source\app C:\Source\app\docs
Sorry to disturb and thanks for your project :)

**Comment by lluiscamino** [comment]
Hi,

Exactly, you have to write the full input and output path. 😃
